# Use the official Node.js image with a specific version
FROM node:20.18.0-alpine

# Set working directory
WORKDIR /app

# Copy application files
COPY app.js /app/app.js

# Specify the command to run your app
ENTRYPOINT ["node", "app.js"]

